### ISSUE TITLE
Include a pure python wheel on PyPI

### ISSUE THREAD

**Issue by cmungall** [gsakkis/pytrie#11]
It would be great if pytrie included a wheel in its pypi distribution - this would allow for use of packages that use pytrie in pyodide and PyScript.

See:
https://github.com/linkml/linkml/issues/1072#issuecomment-1428359097

**Comment by sneakers-the-rat** [comment]
fancy seeing you here. i just came across this trying to do exactly a pyodide thing with linkml. 

@gsakkis if u are willing, this takes approximately 20 seconds <3

```
python -m pip install --upgrade build twine
python -m build
python -m twine upload dist/*
```

**Comment by gsakkis** [comment]
@sneakers-the-rat thanks for the ping, i just uploaded a wheel.

**Comment by sneakers-the-rat** [comment]
tyvm :)
