### ISSUE TITLE
Where can I find the use document

### ISSUE THREAD

**Issue by rsqai** [gsakkis/pytrie#9]
Where can I find the use document

**Comment by gsakkis** [comment]
Normally It should be at [readthedocs](https://pytrie.readthedocs.io/en/latest/) but for some reason they have disappeared, I have to look into it. In the meantime take a look at the [unit tests](https://github.com/gsakkis/pytrie/blob/master/tests/test_trie.py).

**Comment by gsakkis** [comment]
Docs have been updated.
